title: Log                     # title of the site
description: Log your life     # description of the site
url: https://professordeng.com # domain
baseurl: "/log"                # root directory

# Path of site resources
img: /log/assets/img
css: /log/assets/css

## Docs: https://pages.github.com/versions/
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

# default layout of the articles in _post
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Socials
disqus: professordeng
github: professordeng
email: professordeng@qq.com

nav:
- name: Home
  path: /
- name: Project
  path: /pages/project.html
- name: About
  path: /pages/about.html